<a href="https://colab.research.google.com/github/devyoungjin/ML/blob/main/ML_Tensorflow_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1,2,3])
b = tf.constant(4,shape=[1,3])
A = a+b
B = a*b

tf.print(A)

[[5 6 7]]


In [3]:
tf.__version__
# tf version 2.0.0에서는 Session을 정의하고 런하는 과정 생략
# sess = tf.Session()
# sess.run(A)

'2.8.0'

In [4]:
#Interactive Session: 끝나고 세션을 닫음
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

result = tf.multiply(a,b)

# with tf.Session() as sess:
  # output = sess.run(result)
  # print(output)
tf.print(result)

[4 10 18]


In [5]:
x1 = tf.Variable([1,1],dtype=tf.float32)
x2 = tf.Variable([2,2],dtype=tf.float32)
y=x1+x2

# sess = tf.Session()
# init = tf.global_variables_initializer()
# sess.run(init)

tf.print(y)

[3 3]


In [6]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()

x = tf.placeholder(tf.float32,shape=[2,2])
sess = tf.Session()
sess.run(x,feed_dict={x:[[1,2],[3,4]]})


a = tf.placeholder(tf.float32, shape=[2])
b = tf.placeholder(tf.float32, shape=[2])

sum = a+b

sess.run(sum,feed_dict={a:[1,2],b:[3,4]})


Instructions for updating:
non-resource variables are not supported in the long term


array([4., 6.], dtype=float32)

In [7]:
x1 = tf.constant(1,shape=[3])
x2 = tf.constant(2,shape=[3])
output = tf.add(x1,x2)

with tf.Session() as sess:
  result = sess.run(output)
  print(result)

[3 3 3]


In [8]:
x1 = tf.constant(1,shape=[2,3])
x2 = tf.constant(2,shape=[2,3])
output = tf.add(x1,x2)

with tf.Session() as sess:
  result = sess.run(output)
  print(result)

[[3 3 3]
 [3 3 3]]


In [9]:
x1 = tf.constant([[1,2],[3,4]])
x2 = tf.constant([[2],[3]])

#이게 곱이 정확
output1 = tf.matmul(x1,x2)
with tf.Session() as sess:
  result = sess.run(output1)
  print(result)

#혼동 주의
output2 = x1*x2
with tf.Session() as sess:
  result = sess.run(output2)
  print(result)

[[ 8]
 [18]]
[[ 2  4]
 [ 9 12]]


In [10]:
x = [1,2,3,4,5,6,7,8]
x_re = tf.reshape(x,[4,2])
sess =tf.Session()
sess.run(x_re)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)

In [11]:
#-1 은 자동 filling
x_re = tf.reshape(x,[2,-1])
sess = tf.Session()
sess.run(x_re)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

$\displaystyle\min_{\omega}(\omega-4){^2}$

In [12]:
w = tf.Variable(0,dtype=tf.float32)
cost = w*w - 8*w + 16
LR =0.05
optm = tf.train.GradientDescentOptimizer(LR).minimize(cost)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

print(sess.run(w))

0.0


In [13]:
#run one step of gradient descent
sess.run(optm)
print(sess.run(w))

#runs two step of gradient descent
sess.run(optm)
print(sess.run(w))

0.4
0.76


In [14]:
#100 times
for _ in range(100):
  sess.run(optm)

print(sess.run(w))
sess.close()

3.9999142


$\hat y_i =\omega{x_i}+b$

$\displaystyle\min_{\omega,b}$
$\displaystyle\sum_{i=1}^{m}({\hat  y_i-y_i)^2}$

In [15]:
LR = 0.001
n_iter =10000

x = tf.placeholder(tf.float32,[m,1])
y = tf.placeholder(tf.float32,[m,1])

w = tf.Variable([[0]],dtype=tf.float32)
b = tf.Variable([[0]],dtype=tf.float32)

#y_pred = tf.matmul(x,w)+b
y_pred = tf.add(tf.matmul(x,w),b)
loss =tf.square(y_pred-y)
loss =tf.reduce_mean(loss) #sclar

optm = tf.train.GradientDescentOptimizer(LR).minimize(loss)

loss_record=[]

# sess = tf.Session()
# sess.run(tf.global_variables_initializer())

# for epoch in range(n_iter):
#   _,c = sess.run([optm,loss],feed_dict={x:train_x,y:train_y})
#   loss_record.append(c)
# w_val = sess.run(w)
# b_val = sess.run(b)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for epoch in range(n_iter):
    sess.run(optm,feed_dict={x:train_x, y:train_y})
  w_val=sess.run(w)
  b_val=sess.run(b)

sess.close()

NameError: ignored

In [ ]:
#Tensorflow embedded functions
# - tf.nn.sigmoid_cross_entropy_with_logits: for binary classification
# - tf.nn.softmax_cross_entropy_with_logits: for multiclass classification

In [ ]:
LR = 0.05
n_iter = 30000

X = tf.placeholder(tf.float32,[m,3])
y = tf.placeholder(tf.float32,[m,3])

w = tf.Variable(tf.random_normal([3,1]),dtype=tf.float32)


# y_pred = tf.sigmoid(tf.matmul(X,w))
# loss = y*tf.log(y_pred)-(1-y)*tf.log(1-y_pred)
# loss - tf.reduce_mean(loss)

y_pred = tf.matmul(X,w)
loss = tf.nn.sigmoid_cross_entropy_with_logits(logits = y_pred, labels =y) #column
loss = tf.reduce_mean(loss) #scalr

optm = tf.train.GradientDescentOptimizer(LR).minimize(loss)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for epoch in range(n_iter):
    sess.run(optm,feed_dict={X: train_X, y: train_y})

  w_hat = sess.run(w)

σ: sigma/sigmoid함수

λ: lambda/계수 등

θ: 세타/파라메타

$ \forall $: 모든, 임의의

∃: 어떤, 존재한다
 

|B|: cardinality: number of items in set B

||V||: norm:length of vector v

R: the set of real numbers

$ R^n $: real number space of dimension n

$ R^2$ example: (1.3 , -2)

$ \vec{x}\in R^n$: vector X는 N개의 real number value로 구성되어 있다.

$ X \in R^{n*m} $: 행렬X가 mxn크기로 이루어진 행렬이고 엘리먼트들이 real number 이다.

$ 𝑦̂ =𝑤^𝑇𝑥 $:벡터의 내적으로 나타낼 수 있다.

내적(inner product): $ 𝑥⋅𝑦=<𝑥,𝑦>=𝑥^𝑇𝑦$

데이터의 평균: $	\overline{x}=\frac{1}{𝑁}∑𝑖$